enum Notification {
  TEAM_DELETED = "TEAM_DELETED",
  TEAM_RENAMED = "TEAM_RENAMED",
  TEAM_USER_ADDED = "TEAM_USER_ADDED",
  TEAM_USER_REMOVED = "TEAM_USER_REMOVED",

  BOARD_CREATED = "BOARD_CREATED",
  BOARD_RENAMED = "BOARD_RENAMED",
  BOARD_DELETED = "BOARD_DELETED",

  LIST_CREATED = "LIST_CREATED",
  LIST_RENAMED = "LIST_RENAMED",
  LIST_MOVED = "LIST_MOVED",
  LIST_DELETED = "LIST_DELETED",

  CARD_CREATED = "CARD_CREATED",
  CARD_UPDATED = "CARD_UPDATED",
  CARD_MOVED = "CARD_MOVED",
  CARD_DELETED = "CARD_DELETED",
  CARD_USER_ASSIGNED = "CARD_USER_ASSIGNED",
  CARD_USER_UNASSIGNED = "CARD_USER_UNASSIGNED",

  FLAIR_CREATED = "FLAIR_CREATED",
  FLAIR_UPDATED = "FLAIR_UPDATED",
  FLAIR_DELETED = "FLAIR_DELETED",
  FLAIR_ASSIGNED = "FLAIR_ASSIGNED",
  FLAIR_UNASSIGNED = "FLAIR_UNASSIGNED",
}

export default Notification
