enum Notification {
  TEAM_DELETED = "TEAM_DELETED",
  TEAM_RENAMED = "TEAM_RENAMED",
  TEAM_USER_ADDED = "TEAM_USER_ADDED",
  TEAM_USER_REMOVED = "TEAM_USER_REMOVED",

  BOARD_CREATED = "BOARD_CREATED",
  BOARD_RENAMED = "BOARD_RENAMED",
  BOARD_DELETED = "BOARD_DELETED",
}

export default Notification
